server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://git@github.com:pioun/mad-cow-config.git
          searchPaths: '{application}/'
---
spring:
  profiles: git-local
  cloud:
    config:
      server:
        git:
          uri: file:../mad-cow-config
          searchPaths: '{application}/'
          baseDir: target/config