server:
  port: 10001

management:
  server:
    port: 10002
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URI:http://localhost:10101/eureka}
  instance:
    preferIpAddress: true

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pioun/mad-cow-config.git
          searchPaths: '{application}/'
---
spring:
  profiles: git-local
  cloud:
    config:
      server:
        git:
          uri: file:../mad-cow-config
          searchPaths: '{application}/'
          baseDir: target/config